// This file was generated by counterfeiter
package fakes

import (
	"sync"
	"time"

	"github.com/mevansam/cf-cli-api/filters"
)

type FakeEventFilter struct {
	GetEventsForAllAppsInSpaceStub        func(from time.Time, inclusive bool) ([]filters.AppEvent, error)
	getEventsForAllAppsInSpaceMutex       sync.RWMutex
	getEventsForAllAppsInSpaceArgsForCall []struct {
		from      time.Time
		inclusive bool
	}
	getEventsForAllAppsInSpaceReturns struct {
		result1 []filters.AppEvent
		result2 error
	}
	GetEventsForAppStub        func(appGUID string, from time.Time, inclusive bool) ([]filters.AppEvent, error)
	getEventsForAppMutex       sync.RWMutex
	getEventsForAppArgsForCall []struct {
		appGUID   string
		from      time.Time
		inclusive bool
	}
	getEventsForAppReturns struct {
		result1 []filters.AppEvent
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeEventFilter) GetEventsForAllAppsInSpace(from time.Time, inclusive bool) ([]filters.AppEvent, error) {
	fake.getEventsForAllAppsInSpaceMutex.Lock()
	fake.getEventsForAllAppsInSpaceArgsForCall = append(fake.getEventsForAllAppsInSpaceArgsForCall, struct {
		from      time.Time
		inclusive bool
	}{from, inclusive})
	fake.recordInvocation("GetEventsForAllAppsInSpace", []interface{}{from, inclusive})
	fake.getEventsForAllAppsInSpaceMutex.Unlock()
	if fake.GetEventsForAllAppsInSpaceStub != nil {
		return fake.GetEventsForAllAppsInSpaceStub(from, inclusive)
	} else {
		return fake.getEventsForAllAppsInSpaceReturns.result1, fake.getEventsForAllAppsInSpaceReturns.result2
	}
}

func (fake *FakeEventFilter) GetEventsForAllAppsInSpaceCallCount() int {
	fake.getEventsForAllAppsInSpaceMutex.RLock()
	defer fake.getEventsForAllAppsInSpaceMutex.RUnlock()
	return len(fake.getEventsForAllAppsInSpaceArgsForCall)
}

func (fake *FakeEventFilter) GetEventsForAllAppsInSpaceArgsForCall(i int) (time.Time, bool) {
	fake.getEventsForAllAppsInSpaceMutex.RLock()
	defer fake.getEventsForAllAppsInSpaceMutex.RUnlock()
	return fake.getEventsForAllAppsInSpaceArgsForCall[i].from, fake.getEventsForAllAppsInSpaceArgsForCall[i].inclusive
}

func (fake *FakeEventFilter) GetEventsForAllAppsInSpaceReturns(result1 []filters.AppEvent, result2 error) {
	fake.GetEventsForAllAppsInSpaceStub = nil
	fake.getEventsForAllAppsInSpaceReturns = struct {
		result1 []filters.AppEvent
		result2 error
	}{result1, result2}
}

func (fake *FakeEventFilter) GetEventsForApp(appGUID string, from time.Time, inclusive bool) ([]filters.AppEvent, error) {
	fake.getEventsForAppMutex.Lock()
	fake.getEventsForAppArgsForCall = append(fake.getEventsForAppArgsForCall, struct {
		appGUID   string
		from      time.Time
		inclusive bool
	}{appGUID, from, inclusive})
	fake.recordInvocation("GetEventsForApp", []interface{}{appGUID, from, inclusive})
	fake.getEventsForAppMutex.Unlock()
	if fake.GetEventsForAppStub != nil {
		return fake.GetEventsForAppStub(appGUID, from, inclusive)
	} else {
		return fake.getEventsForAppReturns.result1, fake.getEventsForAppReturns.result2
	}
}

func (fake *FakeEventFilter) GetEventsForAppCallCount() int {
	fake.getEventsForAppMutex.RLock()
	defer fake.getEventsForAppMutex.RUnlock()
	return len(fake.getEventsForAppArgsForCall)
}

func (fake *FakeEventFilter) GetEventsForAppArgsForCall(i int) (string, time.Time, bool) {
	fake.getEventsForAppMutex.RLock()
	defer fake.getEventsForAppMutex.RUnlock()
	return fake.getEventsForAppArgsForCall[i].appGUID, fake.getEventsForAppArgsForCall[i].from, fake.getEventsForAppArgsForCall[i].inclusive
}

func (fake *FakeEventFilter) GetEventsForAppReturns(result1 []filters.AppEvent, result2 error) {
	fake.GetEventsForAppStub = nil
	fake.getEventsForAppReturns = struct {
		result1 []filters.AppEvent
		result2 error
	}{result1, result2}
}

func (fake *FakeEventFilter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getEventsForAllAppsInSpaceMutex.RLock()
	defer fake.getEventsForAllAppsInSpaceMutex.RUnlock()
	fake.getEventsForAppMutex.RLock()
	defer fake.getEventsForAppMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeEventFilter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ filters.EventFilter = new(FakeEventFilter)
